language: go
script:
  - go test
notifications:
  slack:
    secure: ichOzfCyzLFMYKbPlMTprY5eaT9KRZ73gPiuvgDzlMF6zwE8aMg5SZ0h6pvE8/mVubv3Lnr6UeCFz1aMxZtA73CHTf4OpuKGVg0tYZ9MEieK+KqAsJsy3KM3185sn/6raEPMttuL/SI79Ug/Z7KEhgEc0zvgZQiafcVwTv35rOvrrr/XymhZLEZvX+z5DVItGPdWb4Ph6RvR8IleT4V/GK0Lyi9mLq1nru+MUU2qgG132eLHLrXtAyD96k8eDUfTtziQDjMoUMmBnODoqDlrZXlPPNdu0LZrpnAHoPl//3Kvcx8Wsu2dfZfpz/7Ql+4FSzKIMkLkv5f2aWp85+I7iVU9EOrRURdsHITMilmcwqRmWOTKOi78qxugxG7EJtpJlzVWo4A3LLvSf2rBNA9iHe72fp/7INUVQUcvSmIAiRsf4WnOnwjR9CaoLyXDHVjP+N/RBmLbjBAUtAtxw7qNnAY+7PucUh/4cI22J4kTaRH5ZMIeFRZwOHtoMCg5DgdlU1NAGqCLvgl9+mr183w3kH8v8L+DaFnq3N7qk/9tvI2D7dDJZYzDSRlWIVI+yIoDEvq04L4796EFPY8WEJXAbHNSMyzB5RAgCGDYh59aaEiZcZRg9z2tnyVjeaWajyAPLWfzTSFhZwqbAKda53D7at74ESvQOJVZattlOWXbSYM=
